#!/bin/bash
vol=$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | awk '{print $5}' | tr -d '%')
muted=$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | grep -q yes && echo yes)
icon=""
[ -n "$vol" ] && { [ "$muted" = "yes" ] && echo " ${vol}%   " || echo "$icon ${vol}%   "; } || echo "$icon N/A   "
